

networks:
  patient_ms-network:
    driver: bridge

volumes:
  patient_postgres_data:
    driver: local

services:

  registry-service:
    build:
      context: ../registry-service
      dockerfile: Dockerfile
    container_name: registry-service
    restart: always
    ports:
      - "8761:8761"
    networks:
      - patient_ms-network
    environment:
      SERVER_PORT: 8761
      SPRING_PROFILES_ACTIVE: dev
      JAVA_TOOL_OPTIONS: "-Dio.micrometer.system-metrics.enabled=false -Dmanagement.metrics.enable.process=false"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      retries: 5
      start_period: 60s

  config-service:
    build:
      context: ../config-service
      dockerfile: Dockerfile
    container_name: config-service
    restart: always
    ports:
      - "7777:7777"
    networks:
      - patient_ms-network
    env_file:
      - .env.common
      - .env.secrets
      - .env.config-service
    depends_on:
      - registry-service
    entrypoint: ["./wait-for-it.sh", "registry-service:8761", "--", "java", "-jar", "app.jar"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7777/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 90s

  patient-db:
    image: postgres:14.1
    container_name: patient-db
    restart: always
    volumes:
      - patient_postgres_data:/var/lib/postgresql/data
      - ../init-scripts/patient-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file:
      - .env.common
      - .env.secrets
    ports:
      - "5433:5432"
    networks:
      - patient_ms-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U patient"]
      interval: 10s
      timeout: 10s
      retries: 5

  patient-service:
    build:
      context: ../patient-service
      dockerfile: Dockerfile
      args:
        PROFILE: local
    container_name: patient-service
    restart: always
    ports:
      - "8081:8081"
    networks:
      - patient_ms-network
    env_file:
      - .env.common
      - .env.secrets
      - .env.patient-service
    depends_on:
      - registry-service
      - config-service
      - patient-db
    entrypoint: ["bash", "-c", "/app/wait-for-it.sh config-service:7777 -- /app/wait-for-it.sh patient-db:5432 -- java -jar app.jar"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s

  report-service:
    build:
      context: ../report-service
      dockerfile: Dockerfile
      args:
        PROFILE: local
    container_name: report-service
    restart: always
    ports:
      - "7071:7071"
    networks:
      - patient_ms-network
    env_file:
      - .env.common
      - .env.secrets
      - .env.report-service
    depends_on:
      - registry-service
      - config-service
      - patient-service
      - patient-db
    entrypoint: ["./wait-for-it.sh", "patient-service:8081", "--", "java", "-jar", "app.jar"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8083/actuator/health || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s